
[general]
	"Max Distance" = 24
	"Render with Interface Disabled (F1)" = false
	"Height Above Mob" = 0.6
	"Draw Background" = true
	"Background Padding" = 2
	"Background Height" = 6
	"Health Bar Height" = 4
	"Plate Size" = 25
	"Plate Size (Boss)" = 50
	"Show Attributes" = true
	"Show Armor" = true
	"Group Armor (condense 5 iron icons into 1 diamond icon)" = true
	"Color Health Bar by Type (instead of health percentage)" = false
	"HP Text Height" = 14
	"Show Max HP" = true
	"Show Current HP" = true
	"Show HP Percentage" = true
	"Display on Players" = true
	"Display on Bosses" = true
	"Only show the health bar for the entity looked at" = false
	"Show entities with full health" = true
	"Show Debug Info with F3" = true
	#Blacklist uses entity IDs, not their display names. Use F3 to see them in the Neat bar.
	Blacklist = ["minecraft:shulker", "minecraft:armor_stand", "minecraft:cod", "minecraft:salmon", "minecraft:pufferfish", "minecraft:tropical_fish", "jujutsucraft:ticket_gate", "jujutsucraft:red", "jujutsucraft:blue", "jujutsucraft:domain_expansion_entity", "jujutsucraft:entity_black_flash", "jujutsucraft:uzumaki", "jujutsucraft:wooden_ball_1", "jujutsucraft:wooden_spear_1", "jujutsucraft:wooden_spear_2", "jujutsucraft:ticket_gate", "jujutsucraft:thunder_impact", "jujutsucraft:rock_fragment", "jujutsucraft:purple", "jujutsucraft:projectile_bullet_human_projectile", "jujutsucraft:projectile_bullet_blood_projectile", "jujutsucraft:projectile_bullet_cannon_projectile", "jujutsucraft:projectile_bullet_curse_power_projectile", "jujutsucraft:projectile_bullet_flame_projectile", "jujutsucraft:projectile_bullet_skeleton_projectile", "jujutsucraft:black_hole", "jujutsucraft:blood_ball", "jujutsucraft:body_repel", "jujutsucraft:bullet_skull"]

